/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guice.example;

import javax.inject.Inject;

public class CounterPrinter {
    
	private CounterService counterService;

	@Inject
	public CounterPrinter(CounterService counterService) {
		this.counterService = counterService;
	}
	
	public void print()	{
		System.out.println("Counter: " + counterService.incrementAndGet());
	}
	
}
